default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: 123456

development:
  <<: *default
  database: locadora_de_veiculos_development

test:
  <<: *default
  database: locadora_de_veiculos_test

production:
  <<: *default
  database: locadora_de_veiculos_production
  username: postgres
  password: 123456
